# Generated by Django 6.1.1 on 2026-09-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='price',
        ),
        migrations.CreateModel(
            name='CookieSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.cookie')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cookie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cookiesize')),
            ],
        ),
    ]
